# Deploys Redis on Docker container using Ansible Playbook
# Inside ./redis-container, run 'ansible-playbook playbook.yml --ask-become-pass' and enter sudo password when prompted
# Test Redis connection by running 'docker exec -it myredis sh' to enter shell and run 'redis-cli ping'

---
- name: Installing + running Redis on Docker container
  hosts: localhost
  become: true
  gather_facts: no
  vars:
    default_container_image: ubuntu:18.04
    default_container_name: ubuntu-for-redis
    redis_port: 6379
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: "Make sure remote system is initialized correctly"
      raw: 'ln -s /usr/bin/python3 /usr/bin/python'
      register: set_symlink
      failed_when: set_symlink.rc != 0 and set_symlink.rc != 1 
    - name: Pull default Docker image from Ubuntu 18.04
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Create container based on Ubuntu
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: present
        volumes:
        - /data
    - name: Run redis in container
      community.docker.docker_container:
        name: myredis
        image: redis
        command: redis-server --appendonly yes
        state: started
        expose:
        - "{{redis_port}}"
        volumes_from:
        - "{{ default_container_name }}"