# Deploys nginx server on docker container using Ansible Playbook
# Run 'ansible-playbook playbook.yml' and test Nginx connection at localhost:8080

- hosts: localhost
  connection: local
  vars:
    default_container_image: ubuntu:18.04
    default_container_name: ubuntu-for-nginx
  tasks:
    - name: Pull default Docker image from Ubuntu 18.04
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Create container based on Ubuntu
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: present
        volumes:
        - /data
    - name: deploy nginx in docker container
      docker_container:
        image: mynginx
        name: nginx
        state: started
        auto_remove: true
        ports: 
          - "8080:80"
        volumes_from:
        - "{{ default_container_name }}"


